
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: gitia-web-laravel
    container_name: gitia-web-laravel
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: gitia-web
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  web:
    image: 'nginx:alpine'
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
